# Generated by Django 5.1 on 2024-08-08 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articletag_tag_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
