# Generated by Django 5.1 on 2024-08-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_tag_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
    ]
