# Generated by Django 5.1 on 2024-08-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='id_sensor',
            new_name='sensor_id',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='discription',
            new_name='description',
        ),
    ]
